source 'https://rubygems.org'

gem "less", "~> 2.4.0"
gem "middleman", "~> 4.3.8"
gem "middleman-minify-html", "~> 3.3.0"
gem "rack-contrib", "~> 1.2.0"
gem "redcarpet", "~> 3.5.1"
gem "therubyracer", "~> 0.12.0"
gem "thin", "~> 1.5.1"

group :development do
  gem "highline", "~> 1.6.15"
end
